### ISSUE TITLE
Blank values

### ISSUE THREAD

**Issue by Nick-GR** [RickStrahl/Westwind.Globalization#14] opened 2015-02-25 07:57 UTC
Sometimes my website's labels and button texts turn blank. The only way to restore them is to restart the application pool.

Running WebForms on .NET Framework 4

**Comment by Nick-GR** [comment] 2015-02-25 07:58
web.config:
<section name="DbResourceProvider" type="Westwind.Globalization.DbResourceProviderSection,Westwind.Globalization" requirePermission="false"/>

    <add name="ScriptCompressionModule" type="Westwind.Web.ScriptCompressionModule,Westwind.Web"/>
  
    <pages controlRenderingCompatibilityVersion="3.5" clientIDMode="AutoID">
      <namespaces>
        <add namespace="Westwind.Utilities"/>
        <add namespace="Westwind.Web"/>
      </namespaces>
      <controls>
        <add tagPrefix="ww" namespace="Westwind.Web.Controls" assembly="Westwind.Web"/>
      </controls>
    </pages>

**Comment by Nick-GR** [comment] 2015-02-25 07:59
add verb="GET" path="JavaScriptResourceHandler.axd" type="Westwind.Globalization.JavaScriptResourceHandler,Westwind.Globalization"/>

<globalization resourceProviderFactoryType="Westwind.Globalization.DbSimpleResourceProviderFactory,Westwind.Globalization" culture="auto:en-US" uiCulture="auto:en-US"

**Comment by Nick-GR** [comment] 2015-02-25 08:04
Example of calling: Text="<%$ Resources: ZEUS,Button_Xamount %>"

**Comment by RickStrahl** [comment] 2015-02-25 22:28
Are other resources served using HttpContext.GetGlobalResource()/GetLocalResource() also blank or is it just the meta tags?

Meta tags are handled during compilation and we've seen issues that in some cases the ResourceSet reads can fail which results in blank data. I'm asking because this stuff should reload when you hit 'normal' resource links.

Also do things start working when you go the Localization Admin page and click the Reload Resources button?

**Comment by Nick-GR** [comment] 2015-02-26 10:35
Sorry Rick, I don't think I understand your first question. What do you mean by other Resources?

I'll try the "reload resourcers" button when it happens again.

**Comment by RickStrahl** [comment] 2015-02-26 23:21
Not implicit resources. Try putting in DbRes.T("ResourceId","ResourceSetName") with the values set appropriately. I'm trying to determine whether the issue is that the actual resource sets aren't loading or whether it's the Implicit Resource Provider used by the Web Forms controls.

The Db providers should always be able to recover from a failure of any kind - when the ResourceSets are empty it'll just retry. The Implicit provider is driven by Microsoft's internal logic so it won't retry if something goes wrong. I suspect it's the latter which would point to a problem in the implicit resource provider.

**Comment by Nick-GR** [comment] 2015-02-27 10:28
Thanks, I'll try the DbRes.T method!
btw there is no "reload Resources" button in admin page. I guess you meant refresh?

**Comment by RickStrahl** [comment] 2015-02-28 02:10
Which provider are you using? The DbSimpleResource provider or DbResourceProvider? If you're using one or the other could you try switching? One uses the default handling that ASP.NET uses (DbSimpleResourceProvider) the other uses a custom implementation. I suspect the custom implementation will fail more gracefully and at least give you the resource label values.

**Comment by Nick-GR** [comment] 2015-03-01 21:28
I'll try switching. I am using Simple now..

**Comment by Nick-GR** [comment] 2015-03-03 11:55
Reloading in the localizanadmin page didnt help. Neither did the "recycle app" button... I have no switched to DbResourceProvider.. Let's see what happens.

**Comment by RickStrahl** [comment] 2015-03-13 03:30
Any change?

FWIW, I've also seen this behavior but it's a side effect of the way Microsoft handles 'implicit' resources for WebForms pages (Meta tags, Resource Expressions). 

Essentially implicit resources are created when the app/page is **compiled**. If the resources are missing for whatever reason when the app is compiled the resources will not be loaded. For this reason implicit resources can be very brittle as they can be very susceptible to timing issues or other load issues. One way to mitigate this problem might be to force ResourceSets to be already loaded by the time the app hits the first page.

Maybe you can try in `Application_Init()` make a call to a resource in the application - this will force the provider to spin up before an ASPX page gets control and may help insure that resources are more readily available without timeing issues. You can use `HttpContext.GetGlobalResource()` or `HttpContent.GetLocalResource()` to cause providers to get 'pre-loaded'.

Another option is to export your db resources to Resx files for deployment.

Closing this issue for now. You can re-open it if you have additional information to help narrow this down.

**Closed** 2015-03-17 03:40 UTC
